apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: add-service
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: adservice
        namespace: APM-Beverages
      spec:
        type: ClusterIP
        selector:
          app: adservice
        ports:
          - name: grpc
            port: 9555
            targetPort: 9555
  providerConfigRef:
    name: kube-config