apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: cart-service
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: cartservice
        namespace: apm-beverages
      spec:
        type: ClusterIP
        selector:
          app: cartservice
        ports:
          - name: grpc
            port: 7070
            targetPort: 7070
  providerConfigRef:
    name: kube-config