apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: frontend-service
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: frontend
        namespace: apm-beverages
      spec:
        type: ClusterIP
        selector:
          app: frontend
        ports:
          - name: http
            port: 80
            targetPort: 8080
  providerConfigRef:
    name: kube-config