apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: loadgenerator-deploy
spec:
  forProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: loadgenerator
        namespace: APM-Beverages
      spec:
        selector:
          matchLabels:
            app: loadgenerator
        replicas: 1
        template:
          metadata:
            labels:
              app: loadgenerator
            annotations:
              sidecar.istio.io/rewriteAppHTTPProbers: "true"
          spec:
            tolerations:
            nodeSelector:
            terminationGracePeriodSeconds: 5
            restartPolicy: Always
            containers:
              - name: main
                ports:
                  - containerPort: 8089
                image: quay.io/signalfuse/microservices-demo-loadgenerator:433c23881a
                env:
                  - name: FRONTEND_ADDR
                    value: "frontend:80"
                  - name: USERS
                    value: "10"
                resources:
                  requests:
                    cpu: 300m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
  providerConfigRef:
    name: kube-config