apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: payment-service
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: paymentservice
        namespace: APM-Beverages
      spec:
        type: ClusterIP
        selector:
          app: paymentservice
        ports:
          - name: grpc
            port: 50051
            targetPort: 50051
  providerConfigRef:
    name: kube-config