apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: productcatalog-service-deploy
spec:
  forProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: productcatalogservice
        namespace: apm-beverages
      spec:
        selector:
          matchLabels:
            app: productcatalogservice
        template:
          metadata:
            labels:
              app: productcatalogservice
          spec:
            tolerations:
            nodeSelector:
            terminationGracePeriodSeconds: 5
            containers:
              - name: server
                image: srushtikotak/apm:productcatalogservice2
                ports:
                  - containerPort: 3550
                env:
                  - name: PORT
                    value: "3550"
                  - name: NODE_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.hostIP
                readinessProbe:
                  exec:
                    command: [ "/bin/grpc_health_probe", "-addr=:3550" ]
                livenessProbe:
                  exec:
                    command: [ "/bin/grpc_health_probe", "-addr=:3550" ]
                resources:
                  requests:
                    cpu: 100m
                    memory: 64Mi
                  limits:
                    cpu: 200m
                    memory: 128Mi
  providerConfigRef:
    name: kube-config