apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: recommendation-service
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: recommendationservice
        namespace: apm-beverages
      spec:
        type: ClusterIP
        selector:
          app: recommendationservice
        ports:
          - name: grpc
            port: 8080
            targetPort: 8080
  providerConfigRef:
    name: kube-config